Iter5
vladkonst/metrics-alerting pull request #5
Opened 2024-10-06 18:24 UTC by vladkonst

2024-10-07 17:40 UTC, rktkov requested changes

2024-10-07 17:40 UTC, rktkov commented on internal/storage/storage.go
> +func GetStorage() *MemStorage {
А может тут вернуть 2 интерфейса, и уже ими пользоваться.

2024-10-07 17:40 UTC, rktkov commented on internal/repositories/repositories.go
> +package repositories
Интерфейсы стоит объявлять в месте их использования.

2024-10-07 17:40 UTC, rktkov commented on internal/configs/netAddress.go
> +func (n *NetAddressCfg) Set(s string) error {
Я бы полную валидацию тогда написал, с учетом правил ип адрессации и портов

ip := net.ParseIP(parts[0])
if ip == nil {
return false
}

port, err := strconv.Atoi(parts[1])
if err != nil || port < 0 || port > 65535 {
        return false
}

2024-10-07 17:40 UTC, rktkov commented on handlers/handlers.go
> +	"github.com/vladkonst/metrics-alerting/internal/repositories"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2024-10-07 17:40 UTC, rktkov commented on cmd/agent/main.go
> +	for range ticker.C {
тут может сильный рассинхрон из-за использование общей памяти (переменная  metrics)

2024-10-08 16:52 UTC, vladkonst commented on cmd/agent/main.go
> +	for range ticker.C {
> тут может сильный рассинхрон из-за использование общей памяти (переменная metrics)

@rktkov Можете подсказать, как можно было бы синхронизировать горутины в данном случае? Я верю, что это возможно, но никак не могу понять куда смотреть(

2024-10-08 16:58 UTC, vladkonst commented on internal/storage/storage.go
> +func GetStorage() *MemStorage {
> А может тут вернуть 2 интерфейса, и уже ими пользоваться.

@rktkov Если я объявляю интерфейс в месте использования, в пакете handlers, то возникнет циклический импорт, если я перепишу функцию GetStorage так, чтобы она возвращала интерфейсы. Как думаете, может будет лучше, если инъектировать storage в handler через middleware?

2024-10-21 09:07 UTC, rktkov commented on cmd/agent/main.go
> +	for range ticker.C {
Для этого существуют каналы, но вы еще их не проходили. Поэтому сейчас ничего делать не надо, но когда тему канало изуче, код надо будет переписать с учетом их использования.

2024-10-21 09:13 UTC, rktkov commented on internal/storage/storage.go
> +func GetStorage() *MemStorage {
Не думаю, что там будет циклический импорт при удачной зависимости между компонентами. А если он возникнет, значит это сигнал, что что-то надо изменить в зависимостях. 
А вообще импорты должны выглядеть так
в пакете handlers -> интерфейс storager
в пакет repo ->  импорт handlers и использование storager
в пакте main(например) -> импорт handlers  и repo и склейка их вместе, например при инициализации handlers или middleware.

2024-10-21 09:17 UTC, rktkov approved these changes

2024-10-24 20:54 UTC, merged